# Generated by Django 3.2.9 on 2022-01-31 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=40, verbose_name='비밀번호')),
                ('nickname', models.CharField(max_length=30, unique=True, verbose_name='닉네임')),
                ('intro', models.CharField(blank=True, max_length=100, verbose_name='자기소개')),
                ('image', models.ImageField(upload_to='%Y/%m/%d', verbose_name='프로필 이미지')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
