# Generated by Django 3.2.9 on 2022-02-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='accounts/%Y/%m/%d', verbose_name='프로필 이미지'),
        ),
    ]
