# Generated by Django 3.2.9 on 2022-02-19 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='게시물 제목')),
                ('content', models.TextField(verbose_name='게시물 내용')),
                ('image', models.ImageField(blank=True, upload_to='posts/%Y/%m/%d', verbose_name='게시물 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='게시물 작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='게시물 수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='게시물 작성자')),
            ],
        ),
    ]
